version: "3.5"

services:
  app:
    build: "."
    restart: always
    volumes:
      - "/Users/ty/server/my_grpc_frame/configs:/configs"
      # 挂载证书
      - "/Users/ty/server/my_grpc_frame/certs:/etc/ssl/certs/"
    depends_on:
      - mariadb
    networks:
      - app_net

  mariadb:
    image: mariadb:10.5.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "123"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    volumes:
      - "/Users/ty/mariadb/data:/var/lib/mysql"
      - "/Users/ty/mariadb/log:/var/log/mysql"
      - "/Users/ty/mariadb/conf:/etc/mysql"
    networks:
      - app_net


networks:
  app_net:
    external: true