params:
  service_name: "push_service"
connections:
  consul:
    addr: "localhost:8500"
  mysql:
    push_service:
      host: localhost
      user: root
      password: 123
      port: 3306
      db: push_service
      charset: utf8mb4
  redis:
    push_service:
      host: localhost
      port: 6379
      db: 0
      password:
log:
  runtime:
    path: /logs/
  track:
    path: /errors/

lark.1:
  app_id: "cl***0b"
  app_secret: "sL***FW"
  type: 1
