params:
  service_name: "push_service"
connections:
  consul:
    addr: "consul:8500"
  mysql:
    push_service:
      host: mariadb
      user: root
      password: 123
      port: 3306
      db: push_service
      charset: utf8mb4
  redis:
    push_service:
      host: redis
      port: 6379
      db: 0
      password:
log:
  runtime:
    path: /logs/
  track:
    path: /errors/