params:
  service_name: "user"
connections:
  consul:
    addr: "consul:8500"
  mysql:
    my_grpc_frame:
      host: mariadb
      user: root
      password: 123
      port: 3306
      db: my_grpc_frame
      charset: utf8mb4
  redis:
    my_grpc_frame:
      host: redis
      port: 6379
      db: 0
      password:
log:
  runtime:
    path: /logs/
  track:
    path: /errors/